Models/QuizEdu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CourseManager.Models
{
    public class QuizEdu
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        //public string Category { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public virtual List<QuizQuestion> Questions { get; set; } = new List<QuizQuestion>();
    }
}

Controllers/QuizEdusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManager.Data;
using CourseManager.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using CourseManager.Repositories.Interfaces;

namespace CourseManager.Controllers
{
    public class QuizEdusController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPaymentsRepository paymentsRepository;

        public QuizEdusController(ApplicationDbContext context, IPaymentsRepository paymentsRepository)
        {
            _context = context;
            this.paymentsRepository = paymentsRepository;
        }

        // GET: QuizEdus
        [Authorize(Roles = "Administrator, Teacher, User")]
        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole("User") && !UserHasPayment(this.User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("MissingPayment", "Administration");
            }
            return View(await _context.QuizEdus.ToListAsync());
        }

        // GET: QuizEdus/Details/5
        [Authorize(Roles = "Administrator, Teacher, User")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizEdu = await _context.QuizEdus
                .Include("Questions")
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quizEdu == null)
            {
                return NotFound();
            }

            return View(quizEdu);
        }

        // GET: QuizEdus/Create
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: QuizEdus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,UserId")] QuizEdu quizEdu)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                quizEdu.UserId = userId;
                _context.Add(quizEdu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quizEdu);
        }

        // GET: QuizEdus/Edit/5
        [Authorize(Roles = "Administrator, Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizEdu = await _context.QuizEdus.FindAsync(id);
            if (quizEdu == null)
            {
                return NotFound();
            }
            return View(quizEdu);
        }

        // POST: QuizEdus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,UserId")] QuizEdu quizEdu)
        {
            if (id != quizEdu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quizEdu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuizEduExists(quizEdu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quizEdu);
        }

        // GET: QuizEdus/Delete/5
        [Authorize(Roles = "Administrator, Teacher")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizEdu = await _context.QuizEdus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quizEdu == null)
            {
                return NotFound();
            }

            return View(quizEdu);
        }

        // POST: QuizEdus/Delete/5
        [Authorize(Roles = "Administrator, Teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quizEdu = await _context.QuizEdus.FindAsync(id);
            _context.QuizEdus.Remove(quizEdu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuizEduExists(int id)
        {
            return _context.QuizEdus.Any(e => e.Id == id);
        }

        private bool UserHasPayment(string userId)
        {
            return _context.Payments.Where(p => p.UserId == userId && DateTime.Today > p.PaymentDate && DateTime.Now < p.EndSubscription).Any();
        }
    }
}

Controllers/QuizQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManager.Data;
using CourseManager.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CourseManager.Controllers
{
    public class QuizQuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuizQuestionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: QuizQuestions
        [Authorize(Roles = "Administrator, Teacher, User")]
        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole("User") && !UserHasPayment(this.User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                return RedirectToAction("MissingPayment", "Administration");
            }
            return View(await _context.QuizQuestions.ToListAsync());
        }

        [Authorize(Roles = "Administrator, Teacher, User")]
        // GET: QuizQuestions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizQuestion = await _context.QuizQuestions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quizQuestion == null)
            {
                return NotFound();
            }

            return View(quizQuestion);
        }


        // GET: QuizQuestions/Create
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Create(string quizName, int quizId)
        {
            ViewBag.QuizId = quizId;
            ViewBag.QuizName = quizName;

            ViewBag.QuizId = new SelectList(_context.QuizEdus, "Id", "Name");

            ViewBag.Options = new List<SelectListItem>
            {
                new SelectListItem{Value="A", Text ="A"},
                new SelectListItem{Value="B", Text ="B"},
                new SelectListItem{Value="C", Text ="C"},
                new SelectListItem{Value="D", Text ="D"}
            };
            return View();
        }

        // POST: QuizQuestions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(QuizQuestion quizQuestion)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                quizQuestion.UserId = userId;
                _context.Add(quizQuestion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quizQuestion);
        }


        // POST: QuizQuestions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Administrator, Teacher")]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(IFormCollection formCollection)
        //{
        //    string[] cos = formCollection[""];
        //    if (ModelState.IsValid)
        //    {
        //        var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
        //        quizQuestion.UserId = userId;
        //        _context.Add(quizQuestion);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(quizQuestion);
        //}

        // GET: QuizQuestions/Edit/5
        [Authorize(Roles = "Administrator, Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizQuestion = await _context.QuizQuestions.FindAsync(id);
            if (quizQuestion == null)
            {
                return NotFound();
            }
            return View(quizQuestion);
        }

        // POST: QuizQuestions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,QuizId,AnswerA,AnswerB,AnswerC,AnswerD,CorrectAnswer,UserId")] QuizQuestion quizQuestion)
        {
            if (id != quizQuestion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quizQuestion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuizQuestionExists(quizQuestion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quizQuestion);
        }

        // GET: QuizQuestions/Delete/5
        [Authorize(Roles = "Administrator, Teacher")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quizQuestion = await _context.QuizQuestions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quizQuestion == null)
            {
                return NotFound();
            }

            return View(quizQuestion);
        }

        // POST: QuizQuestions/Delete/5
        [Authorize(Roles = "Administrator, Teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quizQuestion = await _context.QuizQuestions.FindAsync(id);
            _context.QuizQuestions.Remove(quizQuestion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuizQuestionExists(int id)
        {
            return _context.QuizQuestions.Any(e => e.Id == id);
        }

        private bool UserHasPayment(string userId)
        {
            return _context.Payments.Where(p => p.UserId == userId && DateTime.Today > p.PaymentDate && DateTime.Now < p.EndSubscription).Any();
        }

    }
}

Views/QuizEdus/Create.cshtml
@model CourseManager.Models.QuizEdu

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>QuizEdu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/QuizEdus/Delete.cshtml
@model CourseManager.Models.QuizEdu

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuizEdu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/QuizEdus/Details.cshtml
@model CourseManager.Models.QuizEdu

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
    @Html.ActionLink("Add new question", "Create", "QuizQuestions")

<div>
    <h4>QuizEdu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>

    <h3>List of questions</h3>
    @foreach (var item in Model.Questions)
    {
        <div>@(Model.Questions.IndexOf(item)+1) .@item.Question</div>
        <br />
        <div>A @item.AnswerA</div>
        <br />
        <div>B @item.AnswerB</div>
        <br />
        <div>C @item.AnswerC</div>
        <br />
        <div>D @item.AnswerD</div>
        <br />
        <hr />
    }
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |*@
    <br />
    <a asp-action="Index">Back to List</a>
</div>

Views/QuizEdus/Edit.cshtml
@model CourseManager.Models.QuizEdu

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>QuizEdu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/QuizEdus/Index.cshtml
@model IEnumerable<CourseManager.Models.QuizEdu>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if(User.IsInRole("Administrator") || User.IsInRole("Teacher"))
{
    <p>
        <a asp-action="Create">Add new Quiz</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                    @if(User.IsInRole("Administrator") || User.IsInRole("Teacher"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>