Models/QuizAttempt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CourseManager.Models
{
    public class QuizAttempt
    {
        [Key]
        public int Id { get; set; }
        public string QuizId { get; set; }
        public string Answers { get; set; }
        public string UserId { get; set; }
        public int Score { get; set; }
    }
}

Controllers/QuizAttemptsController.cs
using CourseManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace CourseManager.Controllers
{
    public class QuizAttemptsController : Controller
    {
        private readonly ApplicationDbContext context;

        public QuizAttemptsController(ApplicationDbContext context)
        {
            this.context = context;
        }
        [Authorize(Roles = "Administrator, Teacher, User")]
        public IActionResult Index()
        {
            ViewBag.Quizes = context.QuizEdus.ToList();
            return View();
        }

        [Authorize(Roles = "Administrator, Teacher, User")]
        public IActionResult StartQuiz(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            ViewBag.Questions = context.QuizQuestions.Where(p => p.QuizEduId == id).ToList();
            return View();
        }

        [Authorize(Roles = "Administrator, Teacher, User")]
        [HttpPost]
        public IActionResult SubmitQuiz(IFormCollection iform)
        {
            var questionIds = iform.Keys.Where(p => p.Contains("QAns")).ToList();
            //var answers = iform.Keys.First();
            var questionId = Convert.ToInt32(iform.Keys.Where(p=> p.Contains("questionId")).FirstOrDefault().Split('=')[1]);
            var quizId = context.QuizQuestions.Where(p => p.Id == questionId).Select(p => p.QuizEduId).FirstOrDefault();
            var questionsList = context.QuizQuestions.Where(p => p.QuizEduId == quizId).ToList();
            int score = 0;
            for (int i = 0; i < questionIds.Count; i++)
            {
                string answer = questionIds[i].Substring(0, 1);
                if (questionsList[i].CorrectAnswer == answer)
                {
                    score++;
                }
            }

            string color;
            if(score/questionsList.Count() > 0.75)
            {
                color = "green";
            }
            else
            {
                color = "red";
            }
            ViewBag.Score = score + "/" + questionIds.Count();
            ViewBag.Color = color;

            return View("Result");
        }
    }
}

Views/QuizAttempts/Index.cshtml
    @foreach (var item in ViewBag.Quizes)
    {
        <h3><a asp-action="StartQuiz" asp-route-id="@item.Id">@item.Name</a></h3>

    }
@{
}

Views/QuizAttempts/Result.cshtml
<h1>Your score is <u style="color:@ViewBag.Color">@ViewBag.Score</u></h1>

Views/QuizAttempts/StartQuiz.cshtml
<form asp-controller="QuizAttempts" asp-action="SubmitQuiz">
@foreach (var item in ViewBag.Questions)
{
    <li>
        @item.Question

            <input type="hidden" name="questionId=@item.Id" value="@item.Id"/>
                <ol type="A">
                    <ol>
                        <input type="radio" name="AQAns_@item.Id" value="@item.Id"/>
                        @item.AnswerA
                    </ol>
                    <ol>
                        <input type="radio" name="BQAns_@item.Id" value="@item.Id"/>
                        @item.AnswerB
                    </ol>
                    <ol>
                        <input type="radio" name="CQAns_@item.Id" value="@item.Id"/>
                        @item.AnswerC
                    </ol>
                    <ol>
                        <input type="radio" name="DQAns_@item.Id" value="@item.Id"/>
                        @item.AnswerD
                    </ol>
            </ol>
    </li>
}
<input type="submit" value="Submit" />
</form>